### ISSUE TITLE
{Deref, DerefMut} impl for Refinement<T, P>

### ISSUE THREAD

**Issue by jjpe** [2bdkid/refinement#1]
Hi!

I'm trying to integrate `refinement` into my project, and I've kind of hit a little speedbump.
I need access to a `&T`, and `Refinement<T, P>` doesn't offer that ATM.

Would you be open to merging a PR adding an `impl<T, P> std::ops::Deref<Target = T> for Refinement<T, P>`, and then creating a new crates.io release?

**Comment by 2bdkid** [comment]
I published version `0.4.0` with the change.

**Comment by jjpe** [comment]
Awesome, thanks!
